site_name: RADocs
site_url: 'https://docs.retroachievements.org/'
site_description: >-
  RetroAchievements' documentation page.
repo_name: 'televandalist/RADocsTEMP'
repo_url: 'https://github.com/televandalist/RADocsTEMP'
nav:
  - 'RADocs': 
    - Home: 'index.md'
    - RetroAchievements Manifesto: 'ra-manifesto.md'
    - Users Code of Conduct: 'user-coc.md'
    - Global Leaderboard and Achievement Hunting Rules: 'global-leaderboard-and-achievement-hunting-rules.md'
  - 'Players':
    - Players Home: 'players/home.md'
    - RetroArch: 'players/retroarch.md'
    - RALibretro: 'players/ralibretro.md'
    - User FAQ: 'players/userfaq.md'
  - 'Games':
    - Games Home: 'games/games-home.md'
    - Requests: 'games/requests.md'
    - 'Supported Systems':
      - Libretro Core Support: 'games/libretro-core-support.md'
      - Console Specific Tips: 'games/Console-Specific-Tips.md'
      - Game Identification: 'games/Game-Identification.md'
      - Supported Consoles: 'games/supported-consoles.md'
      - Supported but Not Validated: 'games/not-validated.md'
      - Unsupported Consoles: 'games/unsupported-consoles.md'
      - No Console ID: 'games/no-console-id.md'
    - 'Emulators':
      - RAGens: 'games/emulators/RAGens.md'
      - RALibretro: 'games/emulators/RALibretro.md'
      - RAMeka: 'games/emulators/RAMeka.md'
      - RANes: 'games/emulators/RANes.md'
      - RAP64: 'games/emulators/RAP64.md'
      - RAQUASI88: 'games/emulators/RAQUASI88.md'
      - RASnes9x: 'games/emulators/RASnes9x.md'
      - RAVBA: 'games/emulators/RAVBA.md'
  - 'Developers':
    - Developers Home: 'developers/devs-home.md'
    - Developer Code of Conduct: 'developers/dev-coc.md'
    - DevCoC FAQ: 'developers/dev-coc-faq.md'
    - How to Become an Achievement Developer: 'developers/How-to-Become-an-Achievement-Developer.md'
    - Getting Started as an Achievement Developer: 'developers/Getting-Started-as-an-Achievement-Developer.md'
    - Junior Developers: 'developers/juniordevs.md'
    - Code Review Checklist: 'developers/Code-Review-Checklist.md'
    - New Achievement Set Checklist: 'developers/New-Achievement-Set-Checklist.md'
    - Achievement Scoring: 'developers/Achievement-Scoring.md'
    - Content Guidelines: 'developers/contentguidelines.md'
    - Memory Inspector Overview: 'developers/Memory-Inspector-Overview.md'
    - 'Achievement Logic Features':
      - Logic Features Home: 'developers/features/logic-features-home.md'
      - Hit Counts: 'developers/features/hit-counts.md'
      - Delta Values: 'developers/features/delta-values.md'
      - Prior Values: 'developers/features/prior-values.md'
      - 'Flags':
        - ResetIf Flag: 'developers/features/flags/resetif.md'
        - ResetNextIf Flag: 'developers/features/flags/resetnextif.md'
        - PauseIf Flag: 'developers/features/flags/pauseif.md'
        - AndNext and OrNext Flags: 'developers/features/flags/andnext-ornext.md'
        - AddSource Flag: 'developers/features/flags/addsource.md'
        - SubSource Flag: 'developers/features/flags/subsource.md'
        - AddHits and SubHits Flags: 'developers/features/flags/addhits-subhits.md'
        - AddAddress Flag: 'developers/features/flags/addaddress.md'
        - Measured Flag: 'developers/features/flags/measured.md'
        - Trigger Flag: 'developers/features/flags/trigger.md'
      - BitCount Size: 'developers/features/bitcount-size.md'
      - Alt Groups: 'developers/features/alt-groups.md'
      - Value Definition: 'developers/features/value-definition.md'
      - Condition Syntax: 'developers/features/condition-syntax.md'
      - Minimum Required Versions for Logic Features: 'developers/features/minimum-required-versions-for-logic-features.md'
  - 'Artists':
    - Artists Home: 'artists/arthome.md'
    - Badge and Icon Creation: 'artists/Badge-and-Icon-Creation.md'
  - 'Create':
    - Achievement Creation Home: 'create/Achievement-Creation-Home.md'
    - Achievement Creation Tutorials: 'create/Achievement-Creation-Tutorials.md'
    - Logic Examples: 'create/Logic-Examples.md'
    - Syntax: 'create/Syntax.md'
    - 'Real Examples':
      - Real Examples Home: 'create/Real-Examples.md'
      - Using Hit Counts as a Timer: 'create/realexamples/using-hit-counts-as-a-timer.md'
      - Using Delta Values and Hit Counts to Detect an Increment: 'create/realexamples/using-delta-values-and-hit-counts-to-detect-an-increment.md'
      - Circumvent the Problem of a Counter Incrementing Twice in the Same Frame: 'create/realexamples/circumvent-the-problem-of-a-counter-incrementing-twice-in-the-same-frame.md'
      - Creating a Timer with ResetIf Hits based on the Speed of the Game: 'create/realexamples/creating-a-timer-with-resetIf-hits-based-on-the-speed-of-the-game.md'
      - Using Add Source and Deltas for Collectibles or Similar Achievements: 'create/realexamples/addsource-collectibles.md'
    - Achievement Templates: 'create/Achievement-Templates.md'
    - Tips and Tricks: 'create/Tips-and-Tricks.md'
    - Difficulty Scale and Balance: 'create/Difficulty-Scale-and-Balance.md'
    - Achievement Design: 'create/design.md'
    - Set Development Roadmap: 'create/Set-Development-Roadmap.md'
    - Achievement Set Revisions: 'create/Achievement-Set-Revisions.md'
    - Leaderboards: 'create/Leaderboards.md'
    - Rich Presence: 'create/Rich-Presence.md'
    - Working with the Right ROM: 'create/Working-with-the-Right-ROM.md'
    - Achievements for ROM Hacks: 'create/Achievements-for-ROM-hacks.md'
    - Subsets: 'create/Subsets.md'
  - 'Resources':
    - Resources Home: 'resources/Resources-Home.md'
    - Downloads: 'resources/Downloads.md'
    - Free Homebrews: 'resources/Homebrews.md'
    - Links: 'resources/Resources-Links.md'
    - Console ID List: 'resources/Console-ID-List.md'
    - Glossary: 'resources/glossary.md'
  - 'Community':
    - Community Home: 'community/home.md'
    - RANews: 'community/ranews.md'
    - Events:
      - Events Home: 'community/events.md'
      - Devquest: 'community/events/devquest.md'
      - Rollouts: 'community/events/Rollouts.md'
    - 'Discord':
      - Discord Home: 'community/discord.md'
      - RABot: 'community/discord/RABot%2C-the-RA-Discord-Robot.md'
  - 'Support':
    - FAQ: 'support/FAQ.md'
    - Multi Disc Games Tutorial: 'support/Multi-Disc-Games-Tutorial.md'
    - Working with DLC for the PlayStation Portable: 'support/Working-with-DLC-for-the-PlayStation-Portable.md'
    - How to configure OBS Studio to see the popups: 'support/How-to-configure-OBS-Studio-to-see-the-popups.md'
    - My Game Is Not Loading Achievements: 'support/My-game-is-not-loading-achievements.md'
    - System X Wen: 'support/System-X-wen.md'
    - How to Contribute if You Are Not a Developer: 'support/How-to-contribute-if-you-are-not-a-developer.md'
    - Why You Should Not Use the Load State Feature: 'support/Why-you-should-not-use-the-load-state-feature.md'
    - A Message for Achievement Hunters and Completionists About Revisions: 'support/A-message-for-Achievement-Hunters-and-Completionists-about-revisions.md'
    - Editing Docs: 'support/editingdocs.md'
  - 'Other':
    - About Us: 'sort/About-Us.md'
    - Badge Event Creation Policy: 'sort/Badge-Event-Creation-Policy.md'
    - Combining Flags: 'sort/Combining-Flags.md'
    - Contributing with the Docs: 'sort/Contributing-with-the-docs.md'
    - Ensure Tasks are Done in a Specific Order: 'sort/Ensure-Tasks-are-Done-in-a-Specific-Order.md'
    - Forum Labels: 'sort/Forum Labels.md'
    - RALib on Linux: 'sort/How-to-run-RALibretro-on-Linux.md'
    - Scraping Lists: 'sort/HowTo-Scrape-Achievement-List-to-CSV-for-Rescore-and-Revision-Updates.md'
    - LB Bug and Improvement: 'sort/Leaderboard-bug-list-and-improvement-ideas.md'
    - Mem Searching Techniques: 'sort/Memory-Searching-Techniques.md'
    - New Test Overview: 'sort/NEWTEST Overview.md'
    - RA In Review: 'sort/RA-In-Review.md'
    - RA-Trackers: 'sort/RA-Trackers.md'
    - Regional Compatibility: 'sort/Regional-Compatibility.md'
    - Reporting Broken Shit: 'sort/Reporting-a-Broken-Achievement.md'
    - ROM Localization Policy: 'sort/ROM-Localization-policy.md'
    - Site Change Log: 'sort/Site-Change-Log.md'
    - System Memory Mapping: 'sort/Systems-Memory-Mapping.md'
    - Testing for Demo Mode: 'sort/Testing-for-Demo-Mode.md'
    - The Cheevo Workshop: 'sort/The-Cheevo-Workshop.md'
    - Useful Links: 'sort/Useful-Links.md'
    - Conditional Resets: 'sort/Using-a-Conditional-ResetIf.md'

extra:
  version: '0.0.1'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  i18n:
    prev: 'Previous'
    next: 'Next'

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: true
      guess_lang: false
  - markdown.extensions.nl2br
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic:
      mode: accept
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: libretro
      repo: docs
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - pymdownx.tasklist:
      clickable_checkbox: true

theme:
  name: material
  custom_dir: 'docs/theme'
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.top
    - navigation.tabs.sticky
    - content.tabs.link
  palette:
    primary: 'blue'
    accent: 'light blue'
  icon:
    admonition:
      note: fontawesome/solid/sticky-note
      abstract: fontawesome/solid/book
      info: fontawesome/solid/info-circle
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/question-circle
      warning: fontawesome/solid/exclamation-triangle
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

extra_css:
  - stylesheets/codehilite.css
  - stylesheets/tablesort.css
  - stylesheets/dark_theme.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tablesort.js
